version: '3'
services:
  db:
    image: mysql:8.0.17
    ports:
      - 33060:33060
    environment:
      - MYSQL_ROOT_PASSWORD=tk130tmm81
    volumes:
      - db-store:/var/lib/mysql
      - ./mysql/confd:/etc/mysql/conf.d
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true
    environment:
      USER: "root"
      PASSWORD: "password"
volumes:
  db-store:
